version: '3.9'
services:
  db:
    image: postgis/postgis
    container_name: postgis_testdb_container
    restart: always
    ports: 
      - 5432:5432 
    volumes: 
      - ./.test-data/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=test_db  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: true
    volumes: 
      - ./.test-data/pgadmin:/var/lib/pgadmin

      


 
